config/routes.rb
Rails.application.routes.draw do

 resources :topics, only: [:index, :show]

  # resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

   resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  # devise_for :users, controllers: { sessions: "users/sessions" }

  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'
 

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'

end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: {draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged


 def self.most_recent
 	order(created_at: :desc)
 end

 	mount_uploader :image, BlogUploader

	validates_presence_of :title, :body, :status, :topic_id

  belongs_to :topic

  has_many :comments, dependent: :destroy
end 

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  before_action :set_sidebar_topics, except: [:create, :update, :destroy, :toggle_status]

  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all
  
  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
    
    @blogs = Blog.most_recent.page(params[:page]).per(15)
    else
   
    @blogs = Blog.published.most_recent.page(params[:page]).per(15)
    
   end
   @page_title = "My blog | Thomas Molenaar"
   
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    
    if @blog.draft?  
      @blog.published! 
    elsif @blog.published?
      @blog.draft! 
    end
    
    redirect_to blogs_url, notice:'Status updated!'

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :status, :topic_id, :image)
    end

    def set_sidebar_topics
      @sidebar_topics = Topic.with_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
	def gravatar_helper user
		image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 40
	end

	class CodeRayify < Redcarpet::Render::HTML
		def block_code(code, language)
			CodeRay.scan(code, language).div
		end
	end

	def markdown(text)
		coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

		options = {
			fenced_code_blocks: true,
			no_intra_emphasis: true,
			autolink: true,
			lax_html_block: true
		}

		markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
		markdown_to_html.render(text).html_safe
	end
end

app/views/blogs/_blog.html.erb
  <div class="blog-post tile <%= blog.topic_id%> " data-category="<%= blog.topic_id %>" style="background: url(<%= blog.image %>); background-size: cover; max-width: 100%;">
    <div class="blog-tile-bg" >
    <h2 class="blog-post-title"><%= link_to  blog.title.upcase, blog %></h2>
  	 
    <p class="blog-post-meta"><%= 'Published ' + distance_of_time_in_words(blog.created_at, Time.now) + ' ago' %></p>
      
    <% if logged_in?(:site_admin) %>
    	<p class="blog-post-meta">
  		<%= link_to blog.status, toggle_status_blog_path(blog) %> / 
  		<!--
      <%= link_to 'Edit', edit_blog_path(blog) %> / 
  		<%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
      --> </p>
  	<% end %>
    <%= link_to blog do %>
      <span class="icon"><i class="material-icons">arrow_forward</i></span>
      <% end %>
    </div>
  </div>




  <!-- <%= paginate @blogs, theme: 'twitter-bootstrap-4' %> -->

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error  %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :topic_id %>
    <%= f.collection_select(:topic_id, Topic.all, :id, :title,
                    {
                     include_blank: true 
                    },
                    class: "form-control")
    %>
  </div>


  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', rows: 15 %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>
  
  <div class="status-button">
  

    <% Blog.statuses.keys.each do |status| %>
      <%= f.radio_button :status, status %>
      <%= f.label status.to_sym %>
    <% end %>
    

  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">

	<h1>Edit Blog</h1>

	<br>

	<%= render 'form', blog: @blog %>

	<%= link_to 'Show', @blog %> |
	<%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
 


<div class="col-sm-12 blog-main tile-main">
 
   <%= render @blogs %>
</div> 


  <!-- <%= paginate @blogs, theme: 'twitter-bootstrap-4' %> -->

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">

	<h1>New Blog</h1>

	<br>

	<%= render 'form', blog: @blog %>

	<%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/show.html.erb
<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=592dc9ffde4761001225d3fd&product=sticky-share-buttons"></script>
<div class="col-sm-12 blog-main">
   

   <nav class="breadcrumb">
    <%= link_to "Home", root_path, class: "breadcrumb-item" %>
    <%= link_to @blog.topic.title, topic_path(@blog.topic), class: "breadcrumb-item" %>
    <span class="breadcrumb-item active"><%= @blog.title %></span>

    <span class="pull-right">
    <%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog) if logged_in?(:site_admin) %>
    <%= link_to fa_icon('trash'), @blog, method: :delete, data: {confirm: 'Are you sure you want to delete this post?'} if logged_in?(:site_admin) %>
    </span>
    
    
   </nav>


   <div class="blog-body">

   <% if @blog.image? %>

      <%= image_tag(@blog.image, class: 'blog-image') %>

    

    <% end %> 


     <h2 style="color: black;margin-top: 50px;"><%= @blog.title %></h2>

     <p class="blog-topic-title"><%= @blog.topic.title %></p>
      
    </div>
     

     <hr>
     <div class="row">
     <p>
     	<%= markdown @blog.body %>
     </p>
     </div>

   <%= render 'comments/comment_form' %>
   
     <div id="comments" data-blog-id="<%= @blog.id %>">
      <%= render @blog.comments %>
     </div>

   <br>

   <%= link_to 'Back', blogs_path %>
</div>