config/routes.rb
Rails.application.routes.draw do

 resources :topics, only: [:index, :show]

  # resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

   resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  # devise_for :users, controllers: { sessions: "users/sessions" }

  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'
 

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'

end

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Thomas Molenaar</h3>
    <nav class="nav nav-masthead app-nav">
      
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link nav-link-hidden' %>
      
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
   	<a href="#">Back to top</a>
</footer> 

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
	<div class="container">
		<h1 class="blog-title"> - Blog Standard - </h1>
		<p class="lead blog-description"></p>
		
	</div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
	<div class="container">

  	<div class="nav-menu">
    		<nav class="nav blog-nav collapse navbar-collapse ">
    			
						<%= nav_helper 'nav-link' , 'span' %>
	        	<%= login_helper 'nav-link' %>

    		</nav>
    		<div class="social-nav">
   <!--  <h4>Elsewhere</h4> -->
    			<ol class="list-unstyled social-link">
      			<li><a href="https://github.com/Tlmolenaar"><%= fa_icon "github"%></a></li>
      			<li><a href="https://twitter.com/ThoMol84"><%= fa_icon "twitter"%></a></li>
      			<li><a href="https://www.linkedin.com/in/thomas-molenaar-44b9a418/"><%= fa_icon "linkedin"%></a></li>
    			</ol>
  			</div>
  		
  		</div>
	
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="sidebar-nav">

  <div class="topics">
    <!-- <h4>Topics</h4> -->
      <ul class="topic-list filters-button-group">
      <% @sidebar_topics.each do |topic| %>
        <li class="topic-item"><button data-filter=".<%= topic.id %>" ><%= topic.title %></button></li>
      <% end %>
      <li class="topic-item" data-filter="*"><button>All</button></li>
      <ul>
  </div>

  



</div>

app/views/shared/_nav.html.erb
	<div>
      	<%= link_to "Home", root_path %>
      	<%= link_to "About", about_path %>
     	<%= link_to "Contact", contact_path %>
      	<%= link_to "Blog", blogs_path %>
      	<%= link_to "Portfolio", portfolios_path %>
      	<%= login_helper %>
    </div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
  	<p class="float-right" style="color:white;">
  		<% if logged_in?(:site_admin) %>
      		<%= link_to "Create New Portfolio ", new_portfolio_path, class: "portfolio-footer" %>/
    	<% end %>
    	<%= link_to 'View all portfolio items ', portfolios_path, class: "portfolio-footer" %>/
      	<a href="#" class="portfolio-footer">Back to top</a>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Portfoli<span>o<span></h1>
        <!-- <p class="lead text-muted">I love web development and am always eager to explore new <span class="highlight">technologies</span> and <span class="highlight">design.</span>  </p> -->
       
      </div>
    </section>