config/routes.rb
Rails.application.routes.draw do

 resources :topics, only: [:index, :show]

  # resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

   resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  # devise_for :users, controllers: { sessions: "users/sessions" }

  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'
 

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Fredericka+the+Great|Raleway" rel="stylesheet"> 
    <title><%= @page_title%></title>
    <%= csrf_meta_tags %>
    <meta-name="keywords" content="<%= @seo_keywords %>" />
    <%= favicon_link_tag 'favicons/favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'  %>
  </head>

  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <%=  image_tag "background.png", id: 'background' %>
          <%= render "shared/application_nav" %>
          <%= yield %>
          <%= alerts %>
          <%= source_helper %> 
        </div>
      </div>
    </div> 
    <script>
      if(window.location.pathname == "/about" ){
        console.log("about")
        $(document).ready(function() {
          if(!window.location.hash) {
              console.log("not hash")
              window.location = window.location + '#loaded';
              window.location.reload();
        }
    })   
    }
    else{
      console.log("boo!")
    }
</script>     
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @page_title%></title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <%= favicon_link_tag 'favicons/favicon.ico' %> 
    <meta-name="keywords" content="<%= @seo_keywords %>" />
    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'  %>
    <%= javascript_include_tag 'isotope' %>
    <%= javascript_include_tag 'packery'  %>
  </head>

  <body>
    <%= render 'shared/blog_nav' %>
    <%= render 'shared/blog_sidebar' %>
      <div class="container">
          <p style="font-family: Roboto; color: black !important;"><%= link_to 'Write a new blog ', new_blog_path if logged_in?(:site_admin) %> 
          <div class="row">
            <%= yield %>
          </div>
        <!-- <%= render 'shared/blog_footer' %> -->
        <%= alerts %>
        <%= source_helper %>
      </div>
      <script>
        var assignClass = function() {
          var klasses = [ "tile--red", "tile--yellow", "tile--blue", "tile--green", "tile--pink", "tile--purple", "tile--orange", "tile--lime", "tile--cyan", "tile--indigo", "tile--deep-orange", "tile--brown", "tile--amber", "tile--light-green", "tile--teal", "tile--light-blue" ];
          var sizes = ["tile--width2", "tile--large", "tile", "tile"];
          
          $('.blog-post').each( function(){
            // var colourNum = Math.round(Math.random()*14);
            var sizeNum = Math.round(Math.random()*3);
            // var colour = klasses[colourNum];
            var size = sizes[sizeNum];
            // $(this).addClass(colour);
            $(this).addClass(size);

          });

          $('.blog-tile-bg').each( function(){
            var colourNum = Math.round(Math.random()*14);
            var colour = klasses[colourNum];
            $(this).addClass(colour);
          });
        }
        assignClass();
    </script>
    <script>
      var $grid = $('.blog-main').isotope({
          itemSelector: '.blog-post',
          layoutMode: 'packery',
          packery: {
           gutter: 8
          }
        });


    $('.filters-button-group li').on( 'click', 'button', function() {
        console.log("clicked")
        var filterValue = $(this).attr('data-filter');
        console.log(filterValue);
        // filterValue = filterFns[ filterValue ] || filterValue;
        $grid.isotope({ filter: filterValue });
        // $grid.packery('layout');
      });
    </script> 

    <script>
      if(window.location.pathname == "/blogs" ){
        console.log("blogs")
        $(document).ready(function() {
          if(!window.location.hash) {
              console.log("not hash")
              window.location = window.location + '#loaded';
              window.location.reload();
        }
    })   
    }
    else{
      console.log("boo!")
    }
</script>     
  </body>
</html>

app/views/layouts/portfolios.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title%></title>
    <%= csrf_meta_tags %>
    <meta-name="keywords" content="<%= @seo_keywords %>" />
    <%= favicon_link_tag 'favicons/favicon.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">  
    <%= stylesheet_link_tag    'portfolios', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="background">
      <%= render "shared/portfolio_nav" %>
      <%= render "shared/portfolio_masthead" %>
    <%= yield %>
    <%= render 'shared/portfolio_footer' %>
    <%= alerts %>
    <%= source_helper %>
    </div>
  </body>
</html>